import './globals.css';
import 'mapbox-gl/dist/mapbox-gl.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200 flex flex-col min-h-screen`}>
        <header className="sticky bg-white p-4 space-x-2 flex justify-between">
          <Link href="/">Logo</Link>
          <nav className="space-x-2">
            <Link href="/">Homepage</Link>
            <Link href="/explore">Explore</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
};
